language: java
sudo: false
env:
- P4D_VERSION=15.2
- P4D_VERSION=16.1
jdk:
- oraclejdk8
script:
- ./gradlew check
install:
- mkdir -p build/r${P4D_VERSION}
- wget http://cdist2.perforce.com/perforce/r${P4D_VERSION}/bin.linux26x86_64/p4d -O build/r${P4D_VERSION}/p4d
- chmod +x build/r${P4D_VERSION}/p4d
- export PATH=${PATH}:`pwd`/build/r${P4D_VERSION}
- ./gradlew assemble
